### PR TITLE
Updated automated install instructions and install script

### PR DESCRIPTION
**Pull request by TheBearodactyl**
1) I updated the automated install instructions to where the user wouldn't have to clone the repo
(since the script already does this)

2) I found a way to use for do loops for the path to steam and used them to replace the mess that was the install-theme function

### CODE REVIEW

**Comment by Oman395** [comment]
If you're using curl already, why not download the theme itself with curl? Main benefit is that it reduces the amount of stuff you need to download (bc we can just make it download the specific flavor), but it also would remove the git dependency, and maybe even the wget and unzip deps

**Comment by TheBearodactyl** [comment]
> If you're using curl already, why not download the theme itself with curl? Main benefit is that it reduces the amount of stuff you need to download (bc we can just make it download the specific flavor), but it also would remove the git dependency, and maybe even the wget and unzip deps

because you can't download certain directories of git repos (at least not in a script), only the full repositories

**Comment by TheBearodactyl** [comment]
> If you're using curl already, why not download the theme itself with curl? Main benefit is that it reduces the amount of stuff you need to download (bc we can just make it download the specific flavor), but it also would remove the git dependency, and maybe even the wget and unzip deps

I could use curl to download the theme, but using it for metro and the metro patch would just make the script WAY longer than it needs to be. Also, I honestly don't even know why the unzip dependency is still in there considering that it was only needed for SFP

**Comment by Oman395** [comment]
You could make a call to the gh content API, I.E. `https://api.github.com/repos/catppuccin/steam/contents/themes/macchiato`-- it gives a list of files, which you could grep and download. Your call, might be too much of a pain in the ass to be worth it

Plus we cant test it bc githubusercontent just had its SSL cert expire

**Comment by TheBearodactyl** [comment]
> You could make a call to the gh content API, I.E. `https://api.github.com/repos/catppuccin/steam/contents/themes/macchiato`-- it gives a list of files, which you could grep and download. Your call, might be too much of a pain in the ass to be worth it
> 
> Plus we cant test it bc githubusercontent just had its SSL cert expire

There just one problem with that:
using gh would add yet another dependency and the user would also have to log into the GitHub CLI before being able to use the script.

Also, wdym we can't test it, i tested the updated script on my machine like 20 minutes ago and it worked without any problems whatsoever?

**Comment by Oman395** [comment]
>  using gh would add yet another dependency and the user would also have to log into the GitHub CLI before being able to use the script.
? it's an api call, you just curl it
> Also, wdym we can't test it, i tested the updated script on my machine like 20 minutes ago and it worked without any problems whatsoever?
github just had a ton of SSL certificates expire

**Comment by TheBearodactyl** [comment]
> >  using gh would add yet another dependency and the user would also have to log into the GitHub CLI before being able to use the script.
> ? it's an api call, you just curl it
> > Also, wdym we can't test it, i tested the updated script on my machine like 20 minutes ago and it worked without any problems whatsoever?
> github just had a ton of SSL certificates expire

bruh, I'm stupid, i saw gh and assumed you meant the GitHub cli ☠️
I'll update it when i get back home lmao

**Comment by Oman395** [comment]
also looks like the SSL just got renewed. No pressure to do it btw, it's just a tiny time saver

**Comment by TheBearodactyl** [comment]
> also looks like the SSL just got renewed. No pressure to do it btw, it's just a tiny time saver

nevermind, just found out that the GitHub mobile app allows making edits to files in the pull request ui, I'll update it now :D

**Comment by TheBearodactyl** [comment]
> also looks like the SSL just got renewed. No pressure to do it btw, it's just a tiny time saver

Nevermind, apparently the only resources you can use to download a certain directory from a repository are either subversion or a website (which would mean either another dependency would have to be added, or it wouldn't be nearly as quick as it currently is)

**Comment by Dukeatron** [comment]
@Oman395 good to merge?

**Comment by Oman395** [comment]
Should be good to merge if the install is working, can't test rn but it it's functional we can merge prob

**Comment by TheBearodactyl** [comment]
> Should be good to merge if the install is working, can't test rn but it it's functional we can merge prob

just tested it with my main steam install, then tried it after renaming the steam folder (to test the part that happens if the script can't find an installation), both of them work just fine

**Comment by TheBearodactyl** [comment]
@Oman395 good to merge?

**Comment by Oman395** [comment]
Merged, sorry, I forgor

**Comment by TheBearodactyl** [comment]
> Merged, sorry, I forgor

it's fine lol

**Pull request merged**
